### ISSUE TITLE
Mapping Network Drive

### ISSUE THREAD

**Issue by pchan37** [sbu-ces-unofficial/copy-catch#1]
We need to explore how to map network drives under Rust in a cross-platform manner, preferably minimizing user interaction.

**Comment by pchan37** [comment]
There are two parts for this:

- [ ] Mapping the network drive
- [ ] Getting the drive letter of the mapped drive so that we can access it

**Comment by pchan37** [comment]
@morphmeme 
We can simplify the interface to just take source and destination and assume that any network drives has already been mapped.  Thoughts?

**Comment by morphmeme** [comment]
We should make it generic and work for any network drive besides CES drives. The GUI would have a drop down list of saved network drives and there would be an option to add a new one. There’s a batch command for mapping a network drive and as we are mapping it to some letter, we shouldn’t have to worry about getting the drive letter. I don’t think we should look for any existing network drives because that would involve the user having to interact with the drives directly with themselves.

**Comment by pchan37** [comment]
I guess we should have an option where you can check off "Attempt to map network drives".  Generally speaking, the network drives would already be mapped at this point and it seems pointless to map it on a different letter.  If we run the program multiple times, we would use up several letters.

As a side note, we need to look at how we can map network drives programmatically for MacOSX and Linux.

**Comment by morphmeme** [comment]
As long as the program doesn’t crash, the program should automatically eject the drive so we shouldn’t have to worry about several letters. I don’t think we should think about CES unless doing specific rules so we shouldn’t be thinking about it being already mapped. 

Also since CES has special rules for f/s, to make it generic we could create a rule set that you can import/export

**Comment by pchan37** [comment]
then we can just keep the option checked by default, and in the case that you don't want to map the network drive, you don't need to.  Or is that extra needless complexity?

**Comment by pchan37** [comment]
Also, are we gonna support all kinds of network drive protocol?  Like Windows have SMB and Unix have NFS.  I believe CES just utilizes SMB.

**Comment by morphmeme** [comment]
I don't think we need the checkbox because not only is it more complex, if we were to scan the network drives for the correct domain name and reuse it, we should do it anyway regardless of the user.

For the second question, I don't know. I'd have to research. I'd assume we want to support all network drive protocols.

**Comment by pchan37** [comment]
Fair enough.

Mind you since the majority of the people utilizes SMB, I'm thinking we should put NFS on the backlog for the first release.

For MacOS SMB: https://gist.github.com/natritmeyer/6621231 (mount_smbfs seems to be preinstalled)
For Windows SMB: take a look at existing backup script
For Linux SMB: https://www.thomas-krenn.com/en/wiki/Mounting_a_Windows_Share_in_Linux

Some

**Comment by pchan37** [comment]
After reevaluating our needs, we are not gonna implement the functionality to auto-map network drives.
